### ISSUE TITLE
args--command not found

### ISSUE THREAD

**Issue by tsingfa** [MUGE-2021/image-caption-baseline#3]
root@container-002d11b83c-dee70262:/tmp/pycharm_project_477/run_scripts# bash train_caption.sh
train_caption.sh: line 12: $'\r': command not found
Traceback (most recent call last):
  File "../train.py", line 514, in <module>
    cli_main()
  File "../train.py", line 494, in cli_main
    args = options.parse_args_and_arch(parser, modify_parser=modify_parser)
  File "/tmp/pycharm_project_477/fairseq/fairseq/options.py", line 143, in parse_args_and_arch
    raise RuntimeError()
RuntimeError
train_caption.sh: line 14: --dict-file: command not found
train_caption.sh: line 15: --vocab-file: command not found
train_caption.sh: line 16: --save-dir: command not found
train_caption.sh: line 17: --batch-size: command not found
train_caption.sh: line 18: --task: command not found
train_caption.sh: line 19: --encoder-normalize-before: command not found
train_caption.sh: line 20: --decoder-normalize-before: command not found
train_caption.sh: line 21: --layernorm-embedding: command not found
train_caption.sh: line 22: --patch-layernorm-embedding: command not found
train_caption.sh: line 23: --share-all-embeddings: command not found
train_caption.sh: line 24: --share-decoder-input-output-embed: command not found
train_caption.sh: line 25: --arch: command not found
train_caption.sh: line 26: --criterion: command not found
train_caption.sh: line 27: --label-smoothing: command not found
train_caption.sh: line 28: --dropout: command not found
train_caption.sh: line 29: --weight-decay: command not found
train_caption.sh: line 30: --clip-norm: command not found
train_caption.sh: line 31: --lr-scheduler: command not found
train_caption.sh: line 32: --fp16: command not found
train_caption.sh: line 33: --find-unused-parameters: command not found
train_caption.sh: line 34: --user-dir: command not found
train_caption.sh: line 35: --log-format: command not found
train_caption.sh: line 36: --keep-last-epochs: command not found
train_caption.sh: line 37: --fixed-validation-seed: command not found

**Comment by tsingfa** [comment]
> root@container-002d11b83c-dee70262:/tmp/pycharm_project_477/run_scripts# bash train_caption.sh train_caption.sh: line 12: $'\r': command not found Traceback (most recent call last): File "../train.py", line 514, in cli_main() File "../train.py", line 494, in cli_main args = options.parse_args_and_arch(parser, modify_parser=modify_parser) File "/tmp/pycharm_project_477/fairseq/fairseq/options.py", line 143, in parse_args_and_arch raise RuntimeError() RuntimeError train_caption.sh: line 14: --dict-file: command not found train_caption.sh: line 15: --vocab-file: command not found train_caption.sh: line 16: --save-dir: command not found train_caption.sh: line 17: --batch-size: command not found train_caption.sh: line 18: --task: command not found train_caption.sh: line 19: --encoder-normalize-before: command not found train_caption.sh: line 20: --decoder-normalize-before: command not found train_caption.sh: line 21: --layernorm-embedding: command not found train_caption.sh: line 22: --patch-layernorm-embedding: command not found train_caption.sh: line 23: --share-all-embeddings: command not found train_caption.sh: line 24: --share-decoder-input-output-embed: command not found train_caption.sh: line 25: --arch: command not found train_caption.sh: line 26: --criterion: command not found train_caption.sh: line 27: --label-smoothing: command not found train_caption.sh: line 28: --dropout: command not found train_caption.sh: line 29: --weight-decay: command not found train_caption.sh: line 30: --clip-norm: command not found train_caption.sh: line 31: --lr-scheduler: command not found train_caption.sh: line 32: --fp16: command not found train_caption.sh: line 33: --find-unused-parameters: command not found train_caption.sh: line 34: --user-dir: command not found train_caption.sh: line 35: --log-format: command not found train_caption.sh: line 36: --keep-last-epochs: command not found train_caption.sh: line 37: --fixed-validation-seed: command not found

很奇怪，我在windows（自己电脑）下，可以正常运行的代码，但是一到服务器就有这个问题

**Comment by tsingfa** [comment]
云服务器：
usr_parser ArgumentParser(prog='train.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False)
usr_args Namespace(user_dir=None)
input_args None
args: Namespace(all_gather_list_size=16384, amp=False, amp_batch_retries=2, amp_init_scale=128, amp_scale_window=None, arch=None, azureml_logging=False, batch_size=None, batch_size_valid=None, best_checkpoint_metric='loss', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', clip_norm=0.0, combine_valid_subsets=None, cpu=False, cpu_offload=False, criterion='cross_entropy', curriculum=0, data_buffer_size=10, dataset_impl=None, ddp_backend='pytorch_ddp', ddp_comm_hook='none', device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_num_procs=1, distributed_port=-1, distributed_rank=0, distributed_world_size=1, empty_cache_freq=0, fast_stat_sync=False, find_unused_parameters=False, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, fp32_reduce_scatter=False, gen_subset='test', heartbeat_timeout=-1, ignore_unused_valid_subsets=False, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_interval_updates_pattern=-1, keep_last_epochs=-1, load_checkpoint_on_all_dp_ranks=False, localsgd_frequency=3, log_file=None, log_format=None, log_interval=100, lr=[0.25], lr_scheduler='fixed', max_epoch=0, max_tokens=None, max_tokens_valid=None, max_update=0, max_valid_steps=None, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, model_parallel_size=1, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_reshard_after_forward=False, no_save=False, no_save_optimizer_state=False, nprocs_per_node=1, num_shards=1, num_workers=1, on_cpu_convert_precision=False, optimizer=None, optimizer_overrides='{}', patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, plasma_path='/tmp/plasma', profile=False, quantization_config_path=None, required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_logging=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='checkpoints', save_interval=1, save_interval_updates=0, scoring='bleu', seed=1, sentence_avg=False, shard_id=0, simul_type=None, skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, stop_min_lr=-1.0, stop_time_hours=0, suppress_crashes=False, task='translation', tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', update_freq=[1], use_bmuf=False, use_plasma_view=False, use_sharded_state=False, user_dir=None, valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, wandb_project=None, write_checkpoints_asynchronously=False, zero_sharding='none')


计算机：
usr_parser ArgumentParser(prog='train.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False)
usr_args Namespace(user_dir='../user_module')
input_args None
args: Namespace(all_gather_list_size=16384, amp=False, amp_batch_retries=2, amp_init_scale=128, amp_scale_window=None, arch='muge_baseline_large', azureml_logging=False, batch_size=32,
 batch_size_valid=None, best_checkpoint_metric='loss', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', clip_norm=0.1, c
ombine_valid_subsets=None, cpu=False, cpu_offload=False, criterion='label_smoothed_cross_entropy', curriculum=0, data_buffer_size=10, dataset_impl=None, ddp_backend='pytorch_ddp', ddp_
comm_hook='none', device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_num_procs=1, distributed_port
=-1, distributed_rank=0, distributed_world_size=1, empty_cache_freq=0, fast_stat_sync=False, find_unused_parameters=True, finetune_from_model=None, fix_batches_to_gpus=False, fixed_val
idation_seed=7, fp16=True, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, fp32_reduce_scatter=False, gen_subset='test', heartbeat_t
imeout=-1, ignore_unused_valid_subsets=False, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_interval_updates_pattern=-1, keep_last_epochs=5, load_checkpoint_on_all_dp_ranks=
False, localsgd_frequency=3, log_file=None, log_format='simple', log_interval=10, lr=[0.0001], lr_scheduler='polynomial_decay', max_epoch=0, max_tokens=None, max_tokens_valid=None, max
_update=45000, max_valid_steps=None, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, model_parallel_size=1, no_e
poch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_reshard_after_forward=False, no_save=False, no_save_optimizer_state=False, nprocs_per_node=1, num_shards=1,
 num_workers=4, on_cpu_convert_precision=False, optimizer='adam', optimizer_overrides='{}', patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline
_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, plasma_path='/
tmp/plasma', profile=False, quantization_config_path=None, required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_logging=False, reset_lr_scheduler=
False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='../checkpoints/ECommerce-IC', save_interval=10, save_interval_updates=0, seed=1, sentence
_avg=False, shard_id=0, skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, stop_min_lr=-1.0, stop_time_hours=0, suppress_crashes=False, task=
'caption', tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', update_freq=[2], use_bmuf=False, use_plasma_view=False, use_sharded_stat
e=False, user_dir='../user_module', valid_subset='valid', validate_after_updates=0, validate_interval=10, validate_interval_updates=0, wandb_project=None, write_checkpoints_asynchronou
sly=False, zero_sharding='none')

**Comment by tsingfa** [comment]
> usr_args Namespace(user_dir=None)

为什么云服务器里的usr_args Namespace(user_dir=None)，里面user_dir为啥是None?

**Comment by tsingfa** [comment]
usr_args, _ = usr_parser.parse_known_args(input_args)

云服务器：
_： ['../dataset/ECommerce-IC\r', '\r']

计算机：
_：  ['../dataset/ECommerce-IC', '--dict-file', '../utils/cn_tokenizer/dict.txt', '--vocab-file', '../utils/cn_tokenizer/vocab.txt', '--save-dir', '../checkpoints/ECommerce-IC', '--batch-
size', '32', '--task', 'caption', '--encoder-normalize-before', '--decoder-normalize-before', '--layernorm-embedding', '--patch-layernorm-embedding', '--share-all-embeddings', '--share
-decoder-input-output-embed', '--arch', 'muge_baseline_large', '--criterion', 'label_smoothed_cross_entropy', '--label-smoothing', '0.1', '--dropout', '0.1', '--attention-dropout', '0.
1', '--weight-decay', '0.01', '--optimizer', 'adam', '--adam-betas', '(0.9, 0.999)', '--adam-eps', '1e-08', '--clip-norm', '0.1', '--lr-scheduler', 'polynomial_decay', '--lr', '1e-04',
 '--total-num-update', '45000', '--warmup-updates', '2700', '--fp16', '--update-freq', '2', '--find-unused-parameters', '--log-format', 'simple', '--log-interval', '10', '--keep-last-e
pochs', '5', '--fixed-validation-seed', '7', '--save-interval', '10', '--validate-interval', '10', '--max-update', '45000', '--num-workers', '4']

**Comment by tsingfa** [comment]
tmd解决了，问题的本质就是Ubuntu与Win的编译不通（猜的？），实测同一个文件在win下可运行，在linux就报错，但是可以保证的是程序代码本身没错，我猜应该就是编译的问题，因为我是在windows图形化编辑后再传给linux的，就报错了，但是如果是直接传的原始文件（不能经过windows编辑），再运行就正常了。。。
